repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0  # Specify the version of detect-secrets you want to use
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
