name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build Docker image with Podman
      run: |
        podman build -t username/myapp:${{ github.sha }} .

    - name: Push Docker image to registry
      run: |
        podman push username/myapp:${{ github.sha }} docker://docker.io/username/myapp:${{ github.sha }}

    - name: Set up Kubectl
      run: |
        sudo apt-get install -y kubectl

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
